import 'package:task_planner/DateTimeConverter.dart';
import 'package:floor/floor.dart';
import 'package:sqflite/sqflite.dart' as sqflite;
import 'dart:async';

import 'task.dart';
import 'task_dao.dart';
import 'DateTimeConverter.dart';

part 'task_database.g.dart'; // This will be generated by the build runner


@TypeConverters([DateTimeConverter])
@Database(version: 1, entities: [Task])
abstract class TaskDatabase extends FloorDatabase {
  TaskDao get taskDao;
}